### ISSUE TITLE
Flashes when changing theme mode 

### ISSUE THREAD

**Issue by Liang-zy** [ukui/ukui-kwin#18]
Version：20.04LTS
ISO：ubuntukylin-20.04-0528-amd64.iso
Test environment：Lenovo ThinkPad-X1-Yoga、Lenovo Thinkpad-T430i

Actual results:
Control panel-personalization-theme, after changing the theme, a black screen will flash, and then switch to the corresponding theme mode.
控制面板--个性化--主题，更换主题后，会闪一下黑屏，之后切换到对应主题模式下。

**Comment by kylin-ccn** [comment]
这个是kde的机制，切换主题后，需要重新渲染，重新渲染就会闪一下，机子速度快的话体验相对较好，机子卡的话，可能会黑一下屏
