### ISSUE TITLE
GUI & Icon scaling issues and white titlebars on dark theme

### ISSUE THREAD

**Issue by kevincrans** [ukui/ukui-kwin#2]
The UKUI Desktop automatically scales large on 4K screen even when 100% in the settings, probably because of DPI settings.
Installing another Desktop like Ubuntu-Gnome and going back to UKUI 3, the scale gets even more ridiculous.
The settings app becomes unusable.
Some icons get pixelated during this process.
**This can be fixed by adding settings for dpi & such.**
Also not every title bar responds to dark theme.
**I hope this contributes to the improvement UKUI 3, making more distributions use it:)**

**Comment by Liang-zy** [comment]
20200611 test passed
